# Generated by Django 4.1.1 on 2022-12-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAutor', models.CharField(max_length=100)),
                ('apellidoAutor', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('libro_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLibros.autor')),
            ],
        ),
    ]
