# Generated by Django 4.1.1 on 2022-12-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLibros', '0004_alter_libro_autor_id_alter_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=15, verbose_name='Género'),
        ),
    ]
